copyright:
  name: sheimi
  link: http://blog.sheimi.me

owner:
  name: Rizhen Zhang
  niki: sheimi
  email: sheimi.zhang@gmail.com
  blog: http://blog.sheimi.me
  projects: http://projects.sheimi.me
  phone: (858)382-4693

objective: I'm a first-year M.S. student and want to find a full time position
           after my graduation. I am interested in distributed system, network,
           operating system, web development and mobile development.
